const fs = require('fs');
const path = require('path');
function settingsObject(value) { return value && typeof value === 'object' && !Array.isArray(value) ? value : {}; }
function parseSettings(contents) { const parsed=JSON.parse(contents);if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw new SyntaxError('settings root must be an object');return parsed; }
async function readSettings(file) { return parseSettings(await fs.promises.readFile(file,'utf8')); }
async function syncDirectory(directory) { let handle;try{handle=await fs.promises.open(directory,'r');await handle.sync()}catch{}finally{await handle?.close().catch(()=>{})} }
async function durableWrite(file,contents){const handle=await fs.promises.open(file,'wx',0o600);try{await handle.writeFile(contents,'utf8');await handle.sync()}finally{await handle.close()}}
class SettingsStore {
  constructor(resolvePath,{writeDelayMs=8}={}){if(typeof resolvePath!=='function')throw new TypeError('resolvePath must be a function');this.resolvePath=resolvePath;this.writeDelayMs=Math.max(0,Math.min(1000,Number(writeDelayMs)||0));this.data=null;this.loadPromise=null;this.loadError=null;this.version=0;this.persistedVersion=0;this.attemptedVersion=0;this.writeTimer=null;this.writePromise=null;this.waiters=[]}
  async load(){if(this.data)return this.data;if(!this.loadPromise)this.loadPromise=(async()=>{const target=this.resolvePath(),backup=`${target}.bak`;try{this.data=await readSettings(target);return this.data}catch(primaryError){if(primaryError?.code!=='ENOENT'&&!(primaryError instanceof SyntaxError)){this.loadError=new Error('settings are unreadable',{cause:primaryError});this.data={};return this.data}try{this.data=await readSettings(backup);return this.data}catch(backupError){if(primaryError?.code==='ENOENT'&&backupError?.code==='ENOENT'){this.data={};return this.data}this.loadError=new Error('settings are unreadable or corrupt',{cause:primaryError});this.data={};return this.data}}})();return this.loadPromise}
  async get(key){const data=await this.load();return data[key]}
  async set(key,value){const data=await this.load();if(this.loadError)return false;if(value===undefined)delete data[key];else data[key]=value;const version=++this.version,result=new Promise(resolve=>this.waiters.push({version,resolve}));this.scheduleWrite();return result}
  scheduleWrite(delay=this.writeDelayMs){if(this.writeTimer||this.writePromise)return;this.writeTimer=setTimeout(()=>{this.writeTimer=null;void this.flush()},delay)}
  async flush(){await this.load();if(this.loadError){this.resolveWaiters(this.version,false);return false}if(this.writeTimer){clearTimeout(this.writeTimer);this.writeTimer=null}if(this.writePromise){const requestedVersion=this.version;await this.writePromise;if(this.attemptedVersion<requestedVersion)return this.flush();return this.persistedVersion>=requestedVersion}if(this.persistedVersion>=this.version)return true;const version=this.version;this.attemptedVersion=version;const target=this.resolvePath(),directory=path.dirname(target),backup=`${target}.bak`,nonce=`${process.pid}.${Date.now()}`,temporary=`${target}.${nonce}.tmp`,backupTemporary=`${backup}.${nonce}.tmp`;let serialized;try{serialized=JSON.stringify(this.data)}catch{this.resolveWaiters(version,false);return false}this.writePromise=(async()=>{try{await fs.promises.mkdir(directory,{recursive:true,mode:0o700});await durableWrite(temporary,serialized);try{const previous=await fs.promises.readFile(target,'utf8');parseSettings(previous);await durableWrite(backupTemporary,previous);await fs.promises.rename(backupTemporary,backup)}catch(error){if(error?.code!=='ENOENT'&&!(error instanceof SyntaxError))throw error}await fs.promises.rename(temporary,target);await fs.promises.chmod(target,0o600);await syncDirectory(directory);this.persistedVersion=Math.max(this.persistedVersion,version);this.resolveWaiters(version,true);return true}catch{await fs.promises.unlink(temporary).catch(()=>{});await fs.promises.unlink(backupTemporary).catch(()=>{});this.resolveWaiters(version,false);return false}finally{this.writePromise=null}})();const ok=await this.writePromise;if(this.version>version)this.scheduleWrite(0);return ok}
  resolveWaiters(version,result){const pending=[];for(const waiter of this.waiters){if(waiter.version<=version)waiter.resolve(result);else pending.push(waiter)}this.waiters=pending}
}
module.exports={SettingsStore,settingsObject};
