const fs=require('fs');const path=require('path');const crypto=require('crypto');
const FORMAT='local-aes-gcm-v1',WRAPPED_KEY_FORMAT='safeStorage-wrapped-key-v1';
class LocalSettingsCipher{
 constructor(resolveKeyPath,{vault=null}={}){if(typeof resolveKeyPath!=='function')throw new TypeError('resolveKeyPath must be a function');this.resolveKeyPath=resolveKeyPath;this.vault=vault;this.keyPromise=null}
 vaultAvailable(){try{if(!this.vault?.isEncryptionAvailable?.())return false;return this.vault?.getSelectedStorageBackend?.()!=='basic_text'}catch{return false}}
 async key(){if(!this.keyPromise)this.keyPromise=this.loadOrCreateKey().catch(error=>{this.keyPromise=null;throw error});return this.keyPromise}
 async replaceKeyFile(target,contents){await fs.promises.mkdir(path.dirname(target),{recursive:true,mode:0o700});try{await fs.promises.copyFile(target,`${target}.bak`)}catch(error){if(error?.code!=='ENOENT')throw error}const temporary=`${target}.${process.pid}.${crypto.randomBytes(6).toString('hex')}.tmp`;try{const handle=await fs.promises.open(temporary,'wx',0o600);try{await handle.writeFile(contents);await handle.sync()}finally{await handle.close()}await fs.promises.rename(temporary,target);await fs.promises.chmod(target,0o600)}catch(error){await fs.promises.unlink(temporary).catch(()=>{});throw error}}
 async secureRawKeyFile(target){await fs.promises.chmod(target,0o600);const stat=await fs.promises.stat(target);if(!stat.isFile())throw new Error('Knot settings key is not a regular file');if(process.platform!=='win32'&&(stat.mode&0o077))throw new Error('Knot settings key permissions are not private');if(process.platform!=='win32'&&typeof process.getuid==='function'&&stat.uid!==process.getuid())throw new Error('Knot settings key belongs to another user')}
 wrapped(key){const encrypted=this.vault.encryptString(key.toString('base64'));return JSON.stringify({format:WRAPPED_KEY_FORMAT,data:Buffer.from(encrypted).toString('base64')})}
 async loadOrCreateKey(){const target=this.resolveKeyPath();let existing=null;try{existing=await fs.promises.readFile(target)}catch(error){if(error?.code!=='ENOENT')throw error}if(existing){if(existing.length===32){if(this.vaultAvailable())await this.replaceKeyFile(target,this.wrapped(existing));else await this.secureRawKeyFile(target);return existing}let envelope;try{envelope=JSON.parse(existing.toString('utf8'))}catch{throw new Error('Knot settings key is invalid')}if(envelope?.format!==WRAPPED_KEY_FORMAT||typeof envelope.data!=='string')throw new Error('Knot settings key is invalid');try{if(!this.vaultAvailable())throw new Error('OS credential encryption is unavailable for this settings key');const decoded=this.vault.decryptString(Buffer.from(envelope.data,'base64')),key=Buffer.from(decoded,'base64');if(key.length!==32)throw new Error('Knot settings key is invalid');return key}catch(error){try{const bak=await fs.promises.readFile(target+'.bak');if(bak.length===32)return bak}catch{}throw error}}const key=crypto.randomBytes(32),vaultAvailable=this.vaultAvailable();await this.replaceKeyFile(target,vaultAvailable?this.wrapped(key):key);if(!vaultAvailable)await this.secureRawKeyFile(target);return key}
 async protect(value){if(typeof value!=='string')throw new TypeError('Sensitive setting must be a string');const key=await this.key(),iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',key,iv),data=Buffer.concat([cipher.update(value,'utf8'),cipher.final()]);return{format:FORMAT,iv:iv.toString('base64'),tag:cipher.getAuthTag().toString('base64'),data:data.toString('base64')}}
 async reveal(envelope){if(!envelope||envelope.format!==FORMAT)throw new Error('Unsupported settings envelope');const iv=Buffer.from(String(envelope.iv||''),'base64'),tag=Buffer.from(String(envelope.tag||''),'base64'),data=Buffer.from(String(envelope.data||''),'base64');if(iv.length!==12||tag.length!==16)throw new Error('Invalid settings envelope');const decipher=crypto.createDecipheriv('aes-256-gcm',await this.key(),iv);decipher.setAuthTag(tag);return Buffer.concat([decipher.update(data),decipher.final()]).toString('utf8')}
}
module.exports={FORMAT,WRAPPED_KEY_FORMAT,LocalSettingsCipher};
